### ISSUE TITLE
AV1 publishing support?

### ISSUE THREAD

**Issue by jurisevo** [livekit/server-sdk-go#117]
I am wondering if there is planned supported for AV1 media publishing with this SDK? The whole subject of AV1 support in LiveKit seems a bit murky from the side lines. Is there a technical reason for that?

**Comment by davidzhao** [comment]
AV1 publish support is planned. [Here's the issue](https://github.com/livekit/livekit/issues/942) tracking AV1 within LiveKit.

Closing issue here in favor of the above.
