### ISSUE TITLE
Unexpected behavior of the ConnectToRoom function

### ISSUE THREAD

**Issue by MykolaSolyanko** [livekit/server-sdk-go#156]
Hi there!

### Problem
I am using server-sdk-go to publish a stream to a livekit server. When I call the `lksdk.ConnectToRoom` function and the connection happens through a turn server, then the first time I can’t connect (the logs show `ICE failed`) and, accordingly, the function returns `nil` and `error`, but under the hood there is a reconnect and after two or more attempts the logs show `ICE Connected`, but I can't publish the stream because the `ConnectToRoom` function returned `nil`. 

### Issue
It seems to me that the API of the `lksdk.ConnectToRoom` function is a bit unexpected due to what is happening under the hood.

### version
`github.com/livekit/server-sdk-go v1.0.4`

Thanks for your time!

**Comment by davidzhao** [comment]
Is there any way to reproduce this? I think I understand the issue, but it's difficult for me to see how that happens. 

Have you tried using:

```
room := lksdk.CreateRroom(...)
room.Join(...)
```
