### ISSUE TITLE
Sharing mouse and key events in Screen share

### ISSUE THREAD

**Issue by gedw99** [livekit/server-sdk-go#166]
Is there a way for mouse and keyboard events to be shared when 2 users are screen sharing ? 

Would allow remote pair programming !!

**Comment by davidzhao** [comment]
Hi @gedw99! You can do this with LiveKit today by using the provided data channel. see [data messages](https://docs.livekit.io/client/data-messages/#data-messages).

This would be something an application would implement. It would be outside of the scope of LiveKit itself.

**Comment by gedw99** [comment]
Ok thanks for letting me know
