### ISSUE TITLE
Samplebuilder nil pointer dereference

### ISSUE THREAD

**Issue by nwang92** [livekit/server-sdk-go#196]
I have some code that reads audio data coming in from a webrtc track with `pkg/samplebuilder` similar to how the [filesaver](https://github.com/livekit/server-sdk-go/blob/main/examples/filesaver/main.go) example works.

The meat and potatoes of my code is the following:
```go
sb := samplebuilder.New(MaxAudioLate, &codecs.OpusPacket{}, track.Codec().ClockRate)
...
for {
	pkt, _, err := track.ReadRTP()
	if err != nil {
		break
	}
	sb.Push(pkt)
	
	sample, _ := sb.PopWithTimestamp()
        # do stuff with sample
}
```

When running this code with v1.0.5 of this library, I've seen pretty frequent crashes (every 20min or so?) with a nil pointer dereference. Here's a dump of the stacktrace upon error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x6 pc=0xb72e4a]
goroutine 304 [running]:
github.com/livekit/server-sdk-go/pkg/samplebuilder.(*SampleBuilder).popRtpPackets(0xc000202eb0, 0x0)
        /go/pkg/mod/github.com/livekit/server-sdk-go@v1.0.5/pkg/samplebuilder/samplebuilder.go:417 +0xca
github.com/livekit/server-sdk-go/pkg/samplebuilder.(*SampleBuilder).popSample(0xc000202eb0, 0xf0?)
        /go/pkg/mod/github.com/livekit/server-sdk-go@v1.0.5/pkg/samplebuilder/samplebuilder.go:461 +0x33
github.com/livekit/server-sdk-go/pkg/samplebuilder.(*SampleBuilder).PopWithTimestamp(...)
        /go/pkg/mod/github.com/livekit/server-sdk-go@v1.0.5/pkg/samplebuilder/samplebuilder.go:503
```

Is there a bug in the library here or something I'm doing incorrect with my implementation? For what it's worth, I have `MaxAudioLate = 2` which is the minimum value supported because I care about e2e latency and want to drop packets if they're coming in too late.

**Comment by davidzhao** [comment]
Hey @nwang92, do you have any steps to reproduce this? Does it require a custom source?

**Comment by nwang92** [comment]
I was using a slightly modified version of https://github.com/livekit/server-sdk-go/tree/main/examples/filesaver with the `PopWithTimestamp()` call.

This may have been an issue with the [livekit/livekit](https://github.com/livekit/livekit) itself? I was hitting this nil pointer derefence on v1.3.3, but I can't seem to reproduce it (yet) with v1.3.5

**Comment by nwang92** [comment]
Just an updated: I've hit the nil pinter dereference with v1.3.5 too but it doesn't seem to be as frequent (maybe 30min of activity).

Repro steps:
* Modify https://github.com/livekit/server-sdk-go/tree/main/examples/filesaver and set `maxAudioLate = 2` and use the `PopWithTimestamp()` function
* Start a local livekit server: `livekit-server --dev`
* Run the filesaver example against the local livekit server
* Join local livekit server with https://example.livekit.io/#/
* Sit and wait for nil pointer dereference

**Comment by davidzhao** [comment]
we've decided to revamp our samplebuilder implementation with a new [jitter buffer](https://github.com/livekit/server-sdk-go/tree/main/pkg/jitter). Closing this issue.
