### ISSUE TITLE
golang client sdk please :)

### ISSUE THREAD

**Issue by gedw99** [livekit/server-sdk-go#197]
https://github.com/livekit/client-sdk-rust is a client and uses webgpu.

https://github.com/rajveermalviya/go-webgpu  works great for me as a golang webgpu across platforms.

Would be cool to make a  https://github.com/livekit/client-sdk-go repo with it.

**Comment by gedw99** [comment]
Under the hood the golang client uses rust btw . The same rust package  your rust client uses.

**Comment by gedw99** [comment]
Ah you rust client is designed with livekit-ffi. 

So then this issue is a request for a golang client that leverages your livekit-ffi

As well as a rendering layer that utilises https://github.com/rajveermalviya/go-webgpu to that gui can built with it . 

There is gioui and Fyne gui toolkits with significant users that could benefit from this. 

https://github.com/rajveermalviya/go-webgpu does 2D and 3D and so thanks to its OpenGL and webgpu adapters could really prove a decent golang gui Engine for advanced projects

**Comment by davidzhao** [comment]
That certainly seems possible, but it's quite a significant lift and not planned by the team. If you are interested in hacking on one though, please do take it away!

**Comment by gedw99** [comment]
Ok
