### ISSUE TITLE
Client connected by server-sdk-go is always seen as "IsSpeaking()=true"

### ISSUE THREAD

**Issue by kjs001127** [livekit/server-sdk-go#216]
I'm trying to use server-sdk-go as webrtc client like below

```go
	sampleTrack, err := lksdk.NewLocalSampleTrack(webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeOpus})
	if err != nil {
		return err
	}

	sampleTrack.OnBind(func() {
		if err := sampleTrack.StartWrite(sampleProvider, func() {}); err != nil {
			s.logger.Errorw("Could not start writing", err)
		}
	})

	s.publishedTrack, err = part.PublishTrack(sampleTrack, &lksdk.TrackPublicationOptions{DisableDTX: true})
	if err != nil {
		return err
	}
	s.publishedTrack.SetMuted(false)
```
sampleProvider::CurrentAudioLevel() is implemented by taking RMS of latest pcm frame

```go
func calculateAudioLevel(frame pcm.Frame) uint8 {
	var sum float64
	for i := 0; i < len(frame); i++ {
		sum += math.Pow(float64(frame[i]), 2)
	}
	pcmLen := float64(len(frame))

	rms := math.Sqrt(sum / pcmLen)
	rate := rms / float64(math.MaxUint16)
	return uint8(float64(math.MaxUint8) * rate)
}

```

But participant connected with go-server-sdk is always seen as "IsSpeaking() == true" from other clients (js, android clients) with highlighting enabled even when sampleProvider::CurrentAudioLevel() is returning 0. Is this a known-issue?

**Comment by davidzhao** [comment]
Sorry for the confusion here. The audio level used here is fairly low-level. It follows the RTP extension for audio level and needs to be encoded in a specific format. From the [RFC6464](https://datatracker.ietf.org/doc/html/rfc6464#section-3)

```
The audio level is expressed in -dBov, with values from 0 to 127 representing 0 to -127 dBov.
```
so here, silence would need to be `-127`
