### ISSUE TITLE
update room matadata permission

### ISSUE THREAD

**Issue by lgcshy** [livekit/server-sdk-go#22]
"message": "twirp error unauthenticated: permissions denied"

**code as ffollows:**
type Lc struct {
	LRc *lksdk.RoomServiceClient
}

func NewLc(c *lksdk.RoomServiceClient) *Lc {
	return &Lc{LRc: c}
}

func (l *Lc) updateMataData(room, metadata string) (*livekit.Room, error)  {
	at := auth.NewAccessToken(conf.Key.ApiKey, conf.Key.ApiSecret)
	at.AddGrant(&auth.VideoGrant{RoomAdmin: true, RoomCreate: true, RoomJoin: true})
	tk, _ := at.ToJWT()
	header := make(http.Header)
	header.Set("Authorization", "Bearer "+tk)
	ctx, _ := twirp.WithHTTPRequestHeaders(context.Background(), header)
	return l.LRc.RoomService.UpdateRoomMetadata(ctx, &livekit.UpdateRoomMetadataRequest{
		Room:     room,
		Metadata: metadata,
	})
}

then get the error.

**Comment by davidzhao** [comment]
you need to specify the Room name inside the token.
