### ISSUE TITLE
Twirp: No Response From Server

### ISSUE THREAD

**Issue by refaldyrk** [livekit/server-sdk-go#254]
error start track egress twirp error unavailable: no response from servers

i try to track egress in EgressClient *lksdk.EgressClient ->  EggressClient.StartTrackEgress(ctx, trackRequest)

**Comment by davidzhao** [comment]
Do you have Egress server set up? This log could indicate that there is insufficient capacity. This isn't an issue with the SDK since it's only responding with what LiveKit server is reporting.

**Comment by refaldyrk** [comment]
i have a egress server, yes sometime i get log, my server is high cpu capacity, tq for your response
