### ISSUE TITLE
Missing `recorder` and `hidden` flag when starting egress client

### ISSUE THREAD

**Issue by robleroni** [livekit/server-sdk-go#323]
When starting an egress client with e.g. `StartRoomCompositeEgress` the recorder does not have the permission flags `recorder` and `hidden` set. See: https://docs.livekit.io/realtime/concepts/authentication/

Should these be added here?
https://github.com/livekit/server-sdk-go/blob/6974c0b0b8907057b1db2a5ccf80c1ff408f4d79/egressclient.go#L43

Or is there another way to set these grants?

**Comment by davidzhao** [comment]
this is not missing. `roomRecord` allows the client to initiate Egress requests.

Egress service would generate a separate token for the hidden participant to join the room.
