### ISSUE TITLE
Question: why are exactly 2 peer connections used?

### ISSUE THREAD

**Issue by UladzimirTrehubenka** [livekit/server-sdk-go#349]
In [the code](https://github.com/livekit/server-sdk-go/blob/main/engine.go) and in [the doc](https://docs.livekit.io/reference/internals/client-protocol/) we can see, that there are two separate PeerConnection objects. This is OK for 1to1 call, but how about group calls? For SFU and 3 participants we would have per device 1 out + 2 in, however in real - 6, or did I miss something here? Asking because during implementation custom WebRTC client (based on [pion](https://github.com/pion/webrtc), not **server-sdk-go**) and custom app signaling service (between the client and livekit) observed, that the client with one publisher peer and several subscriber peers probably won't work properly with livekit.

**Comment by davidzhao** [comment]
all subscriber tracks are sent down via a **single** peer connection.
