### ISSUE TITLE
When will there be a Java version of the Server SDK?

### ISSUE THREAD

**Issue by hweeeeeei** [livekit/server-sdk-go#36]
We use Java on the back end, and if we use the Go server SDK, we will use Java to call the GO service through RPC.

**Comment by davidzhao** [comment]
hi @hweeeeeei, a Java server SDK isn't currently in our roadmap. However, we would love to see community efforts here. It should be possible by using [Twirp for Java](https://github.com/fajran/protoc-gen-twirp_java_jaxrs)

additionally, you could use the server APIs via HTTP Posts. [details here](https://docs.livekit.io/guides/server-api/)

**Comment by hweeeeeei** [comment]
Thank you for your reply. I will consider encapsulating the Twirp service interface of HTTP calling GO language in Java and using JSON to transmit data.

**Comment by hweeeeeei** [comment]
If I complete the Java-SDK, I will upload it to my Git repository and open source it
