### ISSUE TITLE
Deadlock in TrackSynchronizer

### ISSUE THREAD

**Issue by slabajo** [livekit/server-sdk-go#367]
On TrackSynchronizer, (pkg/synchronizer/track.go the function GetFrameDuration is protected by a Lock. We have found an issue with that because that function may be called from the GetPTS function on the same type that is also protected by the same Lock. Thus the call to GetFrameDuration hangs the goroutine that invoked it forever.

A little more detail here:

from `track.go` file, GetPTS is lock protexted and calls `adjust:`

```
func (t *TrackSynchronizer) GetPTS(pkt *rtp.Packet) (time.Duration, error) {
	t.Lock()
	defer t.Unlock()

	ts, pts, valid := t.adjust(pkt)
	if pts < t.lastPTS {
```

In `adjust` if expected timestamp falls beyond the `maxTSDiff`, pts is resetted:

```
// sanity check
pts := t.getElapsed(ts) + t.ptsOffset
if expected := time.Since(t.startedAt.Add(t.ptsOffset)); pts > expected+maxTSDiff {
	// reset RTP timestamps
	logger.Debugw("resetting track synchronizer", "reason", "pts out of bounds", "pts", pts, "expected", expected)
	ts, pts = t.resetRTP(pkt)
	return ts, pts, false
}

```
On `resetRtp` first thing is to get Frame duration:

```
func (t *TrackSynchronizer) resetRTP(pkt *rtp.Packet) (int64, time.Duration) {
	frames := int64(time.Since(t.lastPacket) / t.GetFrameDuration())


```
`GetFrameDuration`  is lock protected by the same lock than in `GetPTS` and as Go locks are not reentrant, the routine just hangs forever:

```
func (t *TrackSynchronizer) GetFrameDuration() time.Duration {
	t.Lock()
	defer t.Unlock()

	switch t.track.Kind() {
```

**Comment by frostbyte73** [comment]
Fixed in https://github.com/livekit/server-sdk-go/pull/369
