### ISSUE TITLE
Error in Create Room Golang API 

### ISSUE THREAD

**Issue by Matheshwaran-Shan** [livekit/server-sdk-go#42]
Thanks for this wonderful WebRTC infrastructure Livekit
**Issue Description**
I have set up a livekit server and tested with a connection tester with my Host URL and all tests are passed.
When I try to Create Room in golang with host URL, API secret & API key I'm getting this Error **"twirp error internal: failed to do request: Post "wss://myhosturl.com/twirp/livekit.RoomService/CreateRoom": unsupported protocol scheme "wss"** I have used code which you gave in the example.
Can pls help me to solve this issue?

**Comment by lukasIO** [comment]
Hi!
Generally twirp will establish the "connection" via http, not via websockets. 
Have you tried changing your hosturl to `https://myhosturl.com` instead of `wss://myhosturl.com` ?

**Comment by Matheshwaran-Shan** [comment]
Yes, I have tried and I got an error **" Error from intermediary with HTTP status code 404 "Not Found".**
I'm able to Connect to Room as a participant with the host URL "wss://myhosturl.com"  using the "ConnectToRoom" API.

**Comment by davidzhao** [comment]
Can you share the exact code snippet and what values you are passing in?

**Comment by Matheshwaran-Shan** [comment]
The **Snippet for Creating room**. When I run this code I'm getting Error **unsupported protocol scheme "wss"** as I mentioned earlier. I tried with https://myhosturl.com as well.
````
package main
import (
	"context"
	"fmt"
	livekit "github.com/livekit/protocol/livekit"
	lksdk "github.com/livekit/server-sdk-go"
)
func main() {
	host := "wss://myhosturl.com"
	apiKey := "APIGrpoklqasdapwkndvm"
	apiSecret := "gASwASDAFGEasQWERERasMLZAQWv21zwebvnksHB0AFG"

	roomName := "experiment"

	roomClient := lksdk.NewRoomServiceClient(host, apiKey, apiSecret)

	// create a new room
	room, err := roomClient.CreateRoom(context.Background(), &livekit.CreateRoomRequest{
		Name: roomName,
	})
	fmt.Println("[INFO] Response From CreateRoom ", room)
	if err != nil {
		panic(err)
	}

}
````

The code **Snippet for **ConnectToRoom as a Participant****. Here there is no error I'm able to join a room and publish my data.
````
package main

import (
	"fmt"
	livekit "github.com/livekit/protocol/livekit"
	"github.com/livekit/protocol/logger"
	lksdk "github.com/livekit/server-sdk-go"
	"github.com/pion/webrtc/v3"
)

func main() {
	host := "wss://myhosturl.com"
	apiKey := "APIGrpoklqasdapwkndvm"
	apiSecret := "gASwASDAFGEasQWERERasMLZAQWv21zwebvnksHB0AFG"

	roomName := "experiment"

	room, err := lksdk.ConnectToRoom(
		host,
		lksdk.ConnectInfo{
			APIKey:              apiKey,
			APISecret:           apiSecret,
			RoomName:            roomName,
			ParticipantIdentity: "Participant-1",
		},
	)
	fmt.Println("[INFO] Response from Connecting to Room as a Participant", room, err)
	if err != nil {
		panic(err)
	}
}`

**Comment by davidzhao** [comment]
Yes, this is pretty confusing.. RoomService takes in `https` endpoint instead of wss. (Since it's not websocket). We'll improve this handling in the SDK
