### ISSUE TITLE
Not being able to use signalclient after migrate from v1 to v2

### ISSUE THREAD

**Issue by UladzimirTrehubenka** [livekit/server-sdk-go#534]
Observed during migrate from **v1.1.8** to **v2.2.1**:
```
import lksdk "github.com/livekit/server-sdk-go"
// v1.1.8 code
client := lksdk.NewSignalClient()
res, err := client.Join(url, token, &lksdk.ConnectParams{AutoSubscribe: true})
```
in #392 we [can see](https://github.com/livekit/server-sdk-go/pull/392/files#diff-db22f9da506d0e6a0874eee29d06d041ca0afa8c9d74681a846af283252f648fL77) that
```
func (c *SignalClient) Join(urlPrefix string, token string, params *ConnectParams) (*livekit.JoinResponse, error)
```
became
```
func (c *SignalClient) Join(urlPrefix string, token string, params connectParams) (*livekit.JoinResponse, error)
```
So for now function Join() cannot be used outside (only inside the SDK itself),
actually this is broken design - how exported method would use private structure?!

**Comment by davidzhao** [comment]
we don't recommend using SignalClient by itself outside of the SDK itself. what is your use case?

**Comment by UladzimirTrehubenka** [comment]
Custom app server: **mobile -> app server -> livekit** instead direct **mobile -> livekit**

**Comment by UladzimirTrehubenka** [comment]
Is it possible to add something like
```
func (c *SignalClient) JoinWithAutoSubscribe(urlPrefix string, token string, autoSubscribe bool) (*livekit.JoinResponse, error) {
	params := connectParams{AutoSubscribe: autoSubscribe}
	return c.Join(urlPrefix, token, params)
}
```

**Comment by davidzhao** [comment]
in that case, I think it's ok to make connectParams public. would you like to open a PR renaming it to `SignalClientConnectParams` ?

**Comment by UladzimirTrehubenka** [comment]
OK, I am going to create the PR.

**Comment by UladzimirTrehubenka** [comment]
@davidzhao could you please add reviewers?

**Comment by UladzimirTrehubenka** [comment]
@davidzhao any progress?
