### ISSUE TITLE
CreateSIPtrunk undefined

### ISSUE THREAD

**Issue by AmbaCaramba** [livekit/server-sdk-go#546]
After creating simple example for SERVER API list rooms, after `go run` im getting 

> github.com\livekit\server-sdk-go\v2@v2.2.1\sipclient.go:56:21: s.sipClient.CreateSIPTrunk undefined (type livekit.SIP has no field or method CreateSIPTrunk)

Isnt it related to recent PR - https://github.com/livekit/server-sdk-go/pull/543 ?

```
package main

import (
	"log"
	"os"

	"github.com/joho/godotenv"
        livekit "github.com/livekit/protocol/livekit"
	lksdk "github.com/livekit/server-sdk-go/v2"
)

func main() {

	if err := godotenv.Load("development.env"); err != nil {
		log.Fatalf("Error loading .env file")
	}
	apiKey := os.Getenv("LIVEKIT_API_KEY")
	apiSecret := os.Getenv("LIVEKIT_API_SECRET")

	host := ""
	roomClient := lksdk.NewRoomServiceClient(host, apiKey, apiSecret)
	rooms, _ := roomClient.ListRooms(context.Background(), &livekit.ListRoomsRequest{})
	log.Println(rooms)

}
```

**Comment by davidzhao** [comment]
yes, looks like it is.. we'll revert part of this

**Comment by davidzhao** [comment]
ok, it's an compatibility issue between the last server-sdk-go release. Give v2.3.0 a try, it should resolve this issue

**Comment by AmbaCaramba** [comment]
> ok, it's an compatibility issue between the last server-sdk-go release. Give v2.3.0 a try, it should resolve this issue

it worked,  thx
