### ISSUE TITLE
UnpublishTrack should return an error on invalid SID

### ISSUE THREAD

**Issue by qwertzui11** [livekit/server-sdk-go#55]
Hi there

The following code does not return an error

```go
err := localParticipant.UnpublishTrack("some invalid id")
```

In my opinion this function call should result in an error, however currently `err` is `nil`.

It took me quite some time to figure out, that I'm using the wrong id when calling `UnpublishTrack`. Due to `UnpublishTrack` succeeding I looked everywhere else :wink: 

I guess the following line should change: 
https://github.com/livekit/server-sdk-go/blob/bae117cbb731602646a90b5db07df5f7b02a6976/localparticipant.go#L242

Thanks a lot for your time

**Comment by davidzhao** [comment]
that's a great suggestion! let me know you are up for opening a PR for it.

**Comment by qwertzui11** [comment]
Thx. 
Yes I'm up for a PR. I will propose a PR in the upcoming days.
