### ISSUE TITLE
SECURITY ERROR when import  github.com/livekit/server-sdk-go/v2  v2.3.0

### ISSUE THREAD

**Issue by xtqxk** [livekit/server-sdk-go#563]
`github.com/livekit/server-sdk-go/v2 imports
        github.com/gorilla/websocket: github.com/gorilla/websocket@v1.5.2: verifying module: checksum mismatch
        downloaded: h1:IhsoD2hZmkRRR2jvKyztbbsF4KtoCfNkrlaPsqN31MQ=
        sum.golang.org: h1:qoW6V1GT3aZxybsbC6oLnailWnB+qTMVwMreOso9XUw=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.`

There is an issues at: https://github.com/gorilla/websocket/issues/927

This problem prevents users from using it normally

Pls upgrade github.com/gorilla/websocket to v1.5.3

**Comment by davidzhao** [comment]
🤦 that's a bummer.

just released v2.3.1
