### ISSUE TITLE
how to implement a SampleProvider？，I want to send capture screen frame to livekit track directly ,use  NewLocalSampleTrack

### ISSUE THREAD

**Issue by shieruyu** [livekit/server-sdk-go#63]
I want to send  capture screen frame  to livekit  track directly , but I don't know how to implement a SampleProvider,   Here is my code

`
package main

import (
	"errors"
	"fmt"
	"github.com/kbinani/screenshot"
	"github.com/livekit/protocol/auth"
	"github.com/nfnt/resize"
	"github.com/novalagung/gubrak/v2"
	"github.com/pion/webrtc/v3"
	"github.com/pion/webrtc/v3/pkg/media"
	"github.com/pion/webrtc/v3/pkg/media/h264reader"
	"github.com/pion/webrtc/v3/pkg/media/ivfreader"
	"github.com/pion/webrtc/v3/pkg/media/oggreader"
	"image"
	"os"
	"path/filepath"
	"socket-io/demo63/encoders"
	"time"

	lksdk "github.com/livekit/server-sdk-go"
)

func getJoinToken(apiKey, apiSecret, room, identity string) (string, error) {
	at := auth.NewAccessToken(apiKey, apiSecret)
	grant := &auth.VideoGrant{
		RoomJoin: true,
		Room:     room,
	}
	at.AddGrant(grant).
		SetIdentity(identity).
		SetValidFor(time.Hour)

	return at.ToJWT()
}

const (
	// defaults to 30 fps
	defaultH264FrameDuration = 33 * time.Millisecond
	defaultOpusFrameDuration = 20 * time.Millisecond
)

type StreamProvider struct {
	rtc *rtcStreamer
}

func NewStreamProvider() *StreamProvider {
	return &StreamProvider{
		rtc: &rtcStreamer{},
	}
}

func (s *StreamProvider) OnUnbind() error {
	return nil
}

func (s *StreamProvider) OnBind() error {
	return nil
}

func (s *StreamProvider) NextSample() (media.Sample, error) {
	// todo receive from captures screen frame
	sample := media.Sample{
		Data:     []byte{},
		Duration: 33 * time.Millisecond,
	}

	return sample, nil
}

type ScreenGrabber interface {
	Start()
	Frames() <-chan *image.RGBA
	Stop()
	Fps() int
	Screen() *Screen
}

type Screen struct {
	Index  int
	Bounds image.Rectangle
}

type Service interface {
	CreateScreenGrabber(screen Screen, fps int) (ScreenGrabber, error)
	Screens() ([]Screen, error)
}

// XVideoProvider implements the rdisplay.Service interface for XServer
type XVideoProvider struct{}

// XScreenGrabber captures video from a X server
type XScreenGrabber struct {
	fps    int
	screen Screen
	frames chan *image.RGBA
	stop   chan struct{}
}

// CreateScreenGrabber Creates an screen capturer for the X server
func (*XVideoProvider) CreateScreenGrabber(screen Screen, fps int) (ScreenGrabber, error) {
	return &XScreenGrabber{
		screen: screen,
		fps:    fps,
		frames: make(chan *image.RGBA),
		stop:   make(chan struct{}),
	}, nil
}

// Screens Returns the available screens to capture
func (x *XVideoProvider) Screens() ([]Screen, error) {
	numScreens := screenshot.NumActiveDisplays()
	screens := make([]Screen, numScreens)
	for i := 0; i < numScreens; i++ {
		screens[i] = Screen{
			Index:  i,
			Bounds: screenshot.GetDisplayBounds(i),
		}
	}
	return screens, nil
}

// Frames returns a channel that will receive an image stream
func (g *XScreenGrabber) Frames() <-chan *image.RGBA {
	return g.frames
}

// Start initiates the screen capture loop
func (g *XScreenGrabber) Start() {
	delta := time.Duration(1000/g.fps) * time.Millisecond
	go func() {
		for {
			startedAt := time.Now()
			select {
			case <-g.stop:
				close(g.frames)
				return
			default:
				img, err := screenshot.CaptureRect(g.screen.Bounds)
				if err != nil {
					return
				}
				g.frames <- img
				ellapsed := time.Now().Sub(startedAt)
				sleepDuration := delta - ellapsed
				if sleepDuration > 0 {
					time.Sleep(sleepDuration)
				}
			}
		}
	}()
}

// Stop sends a stop signal to the capture loop
func (g *XScreenGrabber) Stop() {
	close(g.stop)
}

// Screen returns a pointer to the screen we're capturing
func (g *XScreenGrabber) Screen() *Screen {
	return &g.screen
}

// Fps returns the frames per sec. we're capturing
func (g *XScreenGrabber) Fps() int {
	return g.fps
}

// NewVideoProvider returns an X Server-based video provider
func NewVideoProvider() (Service, error) {
	return &XVideoProvider{}, nil
}

func resizeImage(src *image.RGBA, target image.Point) *image.RGBA {
	return resize.Resize(uint(target.X), uint(target.Y), src, resize.Lanczos3).(*image.RGBA)
}

type rtcStreamer struct {
	provider *StreamProvider
	stop     chan struct{}
	screen   ScreenGrabber
	encoder  *encoders.Encoder
	size     image.Point
}

func newRTCStreamer(screen ScreenGrabber, encoder *encoders.Encoder, size image.Point) *rtcStreamer {
	return &rtcStreamer{

		stop:    make(chan struct{}),
		screen:  screen,
		encoder: encoder,
		size:    size,
	}
}

func (s *rtcStreamer) startStream() {
	screen := s.screen
	screen.Start()
	frames := screen.Frames()
	for {
		select {
		case <-s.stop:
			screen.Stop()
			return
		case frame := <-frames:
			err := s.stream(frame)
			if err != nil {
				fmt.Printf("Streamer: %v\n", err)
				return
			}
		}
	}
}

func (s *rtcStreamer) stream(frame *image.RGBA) error {
	resized := resizeImage(frame, s.size)
	
	
	payload, err := (*s.encoder).Encode(resized)
	if err != nil {
		return err
	}
	
	if payload == nil {
		return errors.New("No payload")
	}
	//todo  I want to send the payload to provider NextSample()
	return nil
}

func (s *rtcStreamer) close() {
	close(s.stop)
}

func stream() {
	video, err := NewVideoProvider()
	if err != nil {
		fmt.Println()
	}
	screens, err := video.Screens()
	if err != nil {
		fmt.Println(err)
	}
	if len(screens) == 0 {
		fmt.Println("No available screens")
		//return nil, fmt.Errorf("No available screens")
	}
	fmt.Println(screens)
	//
	grabber, err := video.CreateScreenGrabber(screens[0], 30)
	if err != nil {
		fmt.Println(err.Error())
		return
	}
	screen := grabber.Screen()
	sourceSize := image.Point{
		screen.Bounds.Dx(),
		screen.Bounds.Dy(),
	}
	
	//

	encService := encoders.NewEncoderService()
	encoder, err := encService.NewEncoder(encoders.H264Codec, sourceSize, grabber.Fps())
	if err != nil {
		fmt.Println(222, err.Error())
	}

	//
	size, err := encoder.VideoSize()
	if err != nil {
		fmt.Println(err)

	}
	//
	streamer := newRTCStreamer(grabber, &encoder, size)

	go streamer.startStream()
	
}

func main() {
	
	stream()
	rtc()
	select {}
}

func rtc() {
	apiKey := "APIwzS98MehvNfk"
	apiSecret := "qM5fWRUOA7i3ROY41a2cLUU2rfpXvMpYNZRd1AA9WfkA"

	roomName := "myroom"

	randomString := gubrak.RandomString(6)
	fmt.Println(randomString)
	token, err := getJoinToken(apiKey, apiSecret, roomName, randomString)
	if err != nil {
		panic(err)
	}
	fmt.Println(token)

	room, err := lksdk.ConnectToRoomWithToken("ws://81.70.144.184:7880", token)
	if err != nil {
		panic(err)
	}

	ticker := time.NewTicker(time.Second * 2)
	defer ticker.Stop()
	go func() {
		for range ticker.C {

			room.LocalParticipant.PublishData([]byte(fmt.Sprintln(time.Now().UnixNano())), 0, nil)
			if err != nil {
				fmt.Println( err)
			}
		}
	}()

	

	if err != nil {
		fmt.Println(444, err.Error())
		return
	}

	track, err := lksdk.NewLocalSampleTrack(webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeH264})
	if err != nil {
		return
	}
	provider := &StreamProvider{}

	track.OnBind(func() {
		if err := track.StartWrite(provider, func() {
			fmt.Println("track finished")
		}); err != nil {
			fmt.Println(err)
		}
	})

	if _, err = room.LocalParticipant.PublishTrack(track, ""); err != nil {
		fmt.Println(err)
	}

	room.Callback.OnDataReceived = func(data []byte, rp *lksdk.RemoteParticipant) {
		fmt.Println(333, string(data))
	}

}

`

**Comment by davidzhao** [comment]
Sample provider only needs to provide each sample while specifying their duration. See [here](https://github.com/livekit/server-sdk-go/blob/main/filesampleprovider.go) and [here](https://github.com/livekit/livekit-cli/blob/main/pkg/provider/h264looper.go) for examples.
