### ISSUE TITLE
Can you write some examples about Egress?

### ISSUE THREAD

**Issue by nelsonkti** [livekit/server-sdk-go#73]
I configured s3 as per the documentation and returned an error
Error：`twirp error internal: no response from egress service`
I trying to push the stream to the `srs` stream server also prompts this error

I don't know if I misunderstood the documentation

```
host := "ws://localhost:7880"
apiKey := "***"
apiSecret := "***"

ctx := context.Background()
egressClient := lksdk.NewEgressClient(
		host,
		apiKey,
		apiSecret,
)

roomName := "room"
fileRequest := &livekit.RoomCompositeEgressRequest{
		RoomName: roomName,
		Layout:   "speaker-dark",
		Output: &livekit.RoomCompositeEgressRequest_File{
			File: &livekit.EncodedFileOutput{
				FileType: livekit.EncodedFileType_MP4,
				Filepath: "livekit-demo/my-room-test.mp4",
				Output: &livekit.EncodedFileOutput_S3{
					S3: &livekit.S3Upload{
						AccessKey: ***,
						Secret:    ***,
						Region:    ***,
						Bucket:    ***,
						Endpoint:  ***,
					},
				},
			},
		},
	}
	_, err := egressClient.StartRoomCompositeEgress(ctx, fileRequest)
```

**Comment by davidzhao** [comment]
Did you deploy Egress service? See [docs](https://docs.livekit.io/deploy/egress/)

**Comment by nelsonkti** [comment]
I have deployed s3 in the livekit.yaml file, it is Tencent cloud, not AWS
Is it not supported?

**Comment by nelsonkti** [comment]
I checked the docker log and found this prompt, because of this error?
![image](https://user-images.githubusercontent.com/58064299/175907458-b7382dd9-e293-42b1-92b3-fd6fcbc0e2d0.png)
