### ISSUE TITLE
How can I publish multi track in one connection

### ISSUE THREAD

**Issue by ChenMoGe2** [livekit/server-sdk-go#76]
After I invoke aroom, err := lksdk.ConnectToRoom I invoke PublishTrack and how can I publish another track use aroom.Or I have to invoke another connection using broom, err := lksdk.ConnectToRoom?

**Comment by davidzhao** [comment]
You can publish multiple tracks from the same connection. [see example use](https://github.com/livekit/livekit-cli/blob/main/cmd/livekit-cli/join.go#L146) in our CLI

**Comment by ChenMoGe2** [comment]
> You can publish multiple tracks from the same connection. [see example use](https://github.com/livekit/livekit-cli/blob/main/cmd/livekit-cli/join.go#L146) in our CLI

Thank you very much!
