### ISSUE TITLE
Is there a changelog somewhere ?

### ISSUE THREAD

**Issue by EmrysMyrddin** [livekit/server-sdk-go#84]
Is there some changelog somewhere ?
It's difficult to know what changes have been made between each tags and if there is breaking changes like the room creation requiring callbacks.

**Comment by davidzhao** [comment]
Apologies for the breaking change in the API. We will publish a ChangeLog starting with 1.0 release that's coming up soon.

We weren't able to avoid the breaking change this time due to timing issues that would arise otherwise.
